name: Regenerate API Data with New Microsoft Graph Changes after PR Merge

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'config/microsoft-graph.hcl'
      - 'submodules/msgraph-metadata'
      - 'tools/importer-msgraph/**'


concurrency:
  group: 'regendataapi-msgraph-${{ github.head_ref }}'
  cancel-in-progress: true


jobs:
  regenerate-api-data:
    runs-on: custom-linux-xl
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          submodules: recursive

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.20.5'

      - name: Setup .NET
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
        with:
          dotnet-version: 7.0.x

      - name: build and run importer-msgraph-metadata
        id: import-data
        run: |
          cd ./tools/importer-msgraph-metadata
          make tools
          make build
          make import-all-clean
        env:
          PANDORA_LOG: WARN

      - name: then commit the diff
        id: commit-imported-data
        run: |
          git checkout -b data/regeneration-from-${{ github.sha }}-msgraph
          git config user.name "hc-github-team-tf-azure"
          git config user.email "<>"
          ./scripts/conditionally-commit-codegen-changes.sh "data: regenerating based on the latest MSGraph Metadata"

      - name: then conditionally push the branch
        id: push-branch
        if: ${{ steps.commit-versions-config.outputs.has_changes_to_push == 'true' || steps.commit-imported-data.outputs.has_changes_to_push == 'true' }}
        run: |
          git push origin data/regeneration-from-${{ github.sha }}-msgraph

      - name: then conditionally open a pull request
        id: open-pr
        if: ${{ steps.commit-versions-config.outputs.has_changes_to_push == 'true' || steps.commit-imported-data.outputs.has_changes_to_push == 'true' }}
        run: |
          gh pr create --title "$PR_TITLE" --body "$PR_BODY" -H "$PR_SOURCE" -B "$PR_TARGET"
        env:
          PR_TITLE: "Data: Microsoft Graph - regenerating based on ${{ github.sha }}"
          PR_BODY: "This PR is automatically generated based on the commit ${{ github.sha }}"
          PR_SOURCE: "data/regeneration-from-${{ github.sha }}-msgraph"
          PR_TARGET: "main"
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_PANDORA_TOKEN }}
