name: Run the Version Bumper
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'config/**'
      - 'submodules/msgraph-metadata'
      - 'submodules/rest-api-specs'
      - 'tools/version-bumper/**'
  workflow_dispatch: # for manual invocations

jobs:
  run-version-bumper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.21.3'

      - name: Setup .NET
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
        with:
          dotnet-version: 7.0.x

      - name: build and run version-bumper
        id: bump-versions
        run: |
          cd ./tools/version-bumper
          make tools
          make build
          make run

      - name: then commit the diff
        id: commit-versions-config
        run: |
          git checkout -b config/regeneration-from-${{ github.sha }}
          git config user.name "hc-github-team-tf-azure"
          git config user.email "<>"
          ./scripts/conditionally-commit-codegen-changes.sh "config: regenerating based on the latest Swagger"

      - name: then conditionally push the branch
        id: push-branch
        if: ${{ steps.commit-versions-config.outputs.has_changes_to_push == 'true' || steps.commit-imported-data.outputs.has_changes_to_push == 'true' }}
        run: |
          git push origin config/regeneration-from-${{ github.sha }}

      - name: then conditionally open a pull request
        id: open-pr
        if: ${{ steps.commit-versions-config.outputs.has_changes_to_push == 'true' || steps.commit-imported-data.outputs.has_changes_to_push == 'true' }}
        run: |
          gh pr create --title "$PR_TITLE" --body "$PR_BODY" -H "$PR_SOURCE" -B "$PR_TARGET"
        env:
          PR_TITLE: "Config: regenerating based on ${{ github.sha }}"
          PR_BODY: "Updating the Resource Manager configuration based on the commit ${{ github.sha }}"
          PR_SOURCE: "config/regeneration-from-${{ github.sha }}"
          PR_TARGET: "main"
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_PANDORA_TOKEN }}
