name: Regenerate API Data with New Microsoft Graph Changes after PR Merge

# manicminer: disabling until model consistency issue is resolved
on: workflow_dispatch
#  push:
#    branches:
#      - main
#    paths:
#      - '.github/workflows/**'
#      - 'submodules/msgraph-metadata'
#      - 'tools/importer-msgraph/**'


concurrency:
  group: 'regendataapi-msgraph-${{ github.head_ref }}'
  cancel-in-progress: true


jobs:
  regenerate-api-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          submodules: recursive

      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: '1.20.5'

      - name: Setup .NET
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
        with:
          dotnet-version: 7.0.x

      - name: build and run importer-msgraph-metadata
        id: import-data
        run: |
          cd ./tools/importer-msgraph-metadata
          make tools
          make build
          make import
        env:
          SERVICES: "applications,servicePrincipals"

      - name: then commit the diff
        id: commit-imported-data
        run: |
          git checkout -b data/regeneration-from-${{ github.sha }}-msgraph
          git config user.name "hc-github-team-tf-azure"
          git config user.email "<>"
          ./scripts/conditionally-commit-codegen-changes.sh "data: regenerating based on the latest MSGraph Metadata"

      - name: then conditionally push the branch
        id: push-branch
        if: ${{ steps.commit-versions-config.outputs.has_changes_to_push == 'true' || steps.commit-imported-data.outputs.has_changes_to_push == 'true' }}
        run: |
          git push origin data/regeneration-from-${{ github.sha }}-msgraph

      - name: then conditionally open a pull request
        id: open-pr
        if: ${{ steps.commit-versions-config.outputs.has_changes_to_push == 'true' || steps.commit-imported-data.outputs.has_changes_to_push == 'true' }}
        run: |
          gh pr create --title "$PR_TITLE" --body "$PR_BODY" -H "$PR_SOURCE" -B "$PR_TARGET"
        env:
          PR_TITLE: "Data: Microsoft Graph - regenerating based on ${{ github.sha }}"
          PR_BODY: "This PR is automatically generated based on the commit ${{ github.sha }}"
          PR_SOURCE: "data/regeneration-from-${{ github.sha }}-msgraph"
          PR_TARGET: "main"
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_PANDORA_TOKEN }}
