---
name: Regenerate the Go SDK
on:
  push:
    branches:
      - main
    paths:
      - 'data/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
         submodules: recursive

      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.1'

      - name: Regenerate the Go SDK
        run: |
          ./scripts/automation-generate-go-sdk.sh
