---
name: Importer from Rest API Specs (Unit Tests)
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/**'
      - 'swagger'
      - 'tools/importer-rest-api-specs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
        with:
         submodules: recursive
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.6'
      - run: |
          cd ./tools/importer-rest-api-specs
          make test
