---
name: Verify API Definitions can be Mapped
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/**'
      - 'data/**'

jobs:
  test:
    runs-on: custom-linux-xl
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
        with:
          dotnet-version: 7.0.x

      - name: run unit tests
        run: |
          cd ./data
          make test
