---
name: Data API Differ (Unit Tests)
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/**'
      - 'tools/data-api-differ/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          submodules: recursive

      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: ./.go-version

      - name: run unit tests
        run: |
          cd ./tools/data-api-differ
          make test
