---
name: Verify All Microsoft Graph Services can be Imported and Generated
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/**'
      - 'config/microsoft-graph.hcl'

jobs:
  test:
    runs-on: custom-linux-xl
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: recursive

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: ./.go-version

      - name: "Build and Run importer-msgraph-metadata"
        id: import-data
        run: |
          cd ./tools/importer-msgraph-metadata
          echo "Temporarily disabled until this is updated to use the new Data API"
          # make tools
          # make build
          # make import
        env:
          PANDORA_LOG: WARN
