---
name: Go SDK Generator (Unit Tests)
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/**'
      - 'tools/generator-go-sdk/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
         submodules: recursive

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.20.5'

      - name: run unit tests
        run: |
          cd ./tools/generator-go-sdk
          make test
