---
name: Verify All Resource Manager Services can be Imported and Generated
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/**'
      - 'config/**'

jobs:
  test:
    runs-on: custom-linux-xl
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
        with:
          dotnet-version: 7.0.x

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.20.5'

      - name: "Build Data API"
        run: |
          cd ./data
          make build

      - name: "Build and Run importer-rest-api-specs"
        id: import-data
        run: |
          cd ./tools/importer-rest-api-specs
          make tools
          make build
          make import

      - name: "Run the Go SDK Generator"
        run: |
          # go go gadget generator
          ./scripts/automation-generate-go-sdk.sh
