---
name: Verify All Microsoft Graph Services can be Imported and Generated
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/**'
      - 'config/microsoft-graph.hcl'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
        with:
          dotnet-version: 7.0.x

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.20.5'

      - name: "Build Data API"
        run: |
          cd ./data
          make build

      - name: "Build and Run importer-msgraph-metadata"
        id: import-data
        run: |
          cd ./tools/importer-msgraph-metadata
          make tools
          make build
          make import
        env:
          PANDORA_LOG: WARN
